### PR TITLE
Run every_X schedules on fixed times

### LINKED ISSUE #1103: Synchronize Agent Schedules
I think it would be a good idea to put Agent Schedules on a cron like timetable rather than a timetable related to the Huginn launch time.
So when I put an Agent on like "Every 12h", it will be scheduled for Midnight + Noon, rather than every 12 hours from the time when I launched Huginn.
I know that this could be done by using SchedulerAgents, but that would mean one more Agent per scenario, which in my opinion would be overkill.
What do you guys think?

### PR DESCRIPTION
**Pull request by dsander**
Makes the schedules more predictable by running them on fixes hours/minutes instead of X seconds after startup.

Changed the "every 7d" schedule to "every Monday" night to make it clearer when it runs because every 7 days is ambiguous without a explicit start date.

The master branch `rufus-scheduler` is required because it includes a performance improvement to it's cronline parser. Before the `setup` method of `HuginnScheduler` took 5 seconds to run, now its faster than before adding the cronline based schedules (about 0.2s).

Fixes #1103

Possibly related to #1840

Example runtimes:

```
every_1m (*/1 * * * *)
2016-12-29 11:28:00 +0100
2016-12-29 11:29:00 +0100
2016-12-29 11:30:00 +0100
2016-12-29 11:31:00 +0100
2016-12-29 11:32:00 +0100
2016-12-29 11:33:00 +0100
2016-12-29 11:34:00 +0100
2016-12-29 11:35:00 +0100
2016-12-29 11:36:00 +0100
2016-12-29 11:37:00 +0100

every_2m (*/2 * * * *)
2016-12-29 11:28:00 +0100
2016-12-29 11:30:00 +0100
2016-12-29 11:32:00 +0100
2016-12-29 11:34:00 +0100
2016-12-29 11:36:00 +0100
2016-12-29 11:38:00 +0100
2016-12-29 11:40:00 +0100
2016-12-29 11:42:00 +0100
2016-12-29 11:44:00 +0100
2016-12-29 11:46:00 +0100

every_5m (*/5 * * * *)
2016-12-29 11:30:00 +0100
2016-12-29 11:35:00 +0100
2016-12-29 11:40:00 +0100
2016-12-29 11:45:00 +0100
2016-12-29 11:50:00 +0100
2016-12-29 11:55:00 +0100
2016-12-29 12:00:00 +0100
2016-12-29 12:05:00 +0100
2016-12-29 12:10:00 +0100
2016-12-29 12:15:00 +0100

every_10m (*/10 * * * *)
2016-12-29 11:30:00 +0100
2016-12-29 11:40:00 +0100
2016-12-29 11:50:00 +0100
2016-12-29 12:00:00 +0100
2016-12-29 12:10:00 +0100
2016-12-29 12:20:00 +0100
2016-12-29 12:30:00 +0100
2016-12-29 12:40:00 +0100
2016-12-29 12:50:00 +0100
2016-12-29 13:00:00 +0100

every_30m (*/30 * * * *)
2016-12-29 11:30:00 +0100
2016-12-29 12:00:00 +0100
2016-12-29 12:30:00 +0100
2016-12-29 13:00:00 +0100
2016-12-29 13:30:00 +0100
2016-12-29 14:00:00 +0100
2016-12-29 14:30:00 +0100
2016-12-29 15:00:00 +0100
2016-12-29 15:30:00 +0100
2016-12-29 16:00:00 +0100

every_1h (0 */1 * * *)
2016-12-29 12:00:00 +0100
2016-12-29 13:00:00 +0100
2016-12-29 14:00:00 +0100
2016-12-29 15:00:00 +0100
2016-12-29 16:00:00 +0100
2016-12-29 17:00:00 +0100
2016-12-29 18:00:00 +0100
2016-12-29 19:00:00 +0100
2016-12-29 20:00:00 +0100
2016-12-29 21:00:00 +0100

every_2h (0 */2 * * *)
2016-12-29 12:00:00 +0100
2016-12-29 14:00:00 +0100
2016-12-29 16:00:00 +0100
2016-12-29 18:00:00 +0100
2016-12-29 20:00:00 +0100
2016-12-29 22:00:00 +0100
2016-12-30 00:00:00 +0100
2016-12-30 02:00:00 +0100
2016-12-30 04:00:00 +0100
2016-12-30 06:00:00 +0100

every_5h (0 */5 * * *)
2016-12-29 15:00:00 +0100
2016-12-29 20:00:00 +0100
2016-12-30 00:00:00 +0100
2016-12-30 05:00:00 +0100
2016-12-30 10:00:00 +0100
2016-12-30 15:00:00 +0100
2016-12-30 20:00:00 +0100
2016-12-31 00:00:00 +0100
2016-12-31 05:00:00 +0100
2016-12-31 10:00:00 +0100

every_12h (0 */12 * * *)
2016-12-29 12:00:00 +0100
2016-12-30 00:00:00 +0100
2016-12-30 12:00:00 +0100
2016-12-31 00:00:00 +0100
2016-12-31 12:00:00 +0100
2017-01-01 00:00:00 +0100
2017-01-01 12:00:00 +0100
2017-01-02 00:00:00 +0100
2017-01-02 12:00:00 +0100
2017-01-03 00:00:00 +0100

every_1d (0 0 */1 * *)
2016-12-30 00:00:00 +0100
2016-12-31 00:00:00 +0100
2017-01-01 00:00:00 +0100
2017-01-02 00:00:00 +0100
2017-01-03 00:00:00 +0100
2017-01-04 00:00:00 +0100
2017-01-05 00:00:00 +0100
2017-01-06 00:00:00 +0100
2017-01-07 00:00:00 +0100
2017-01-08 00:00:00 +0100

every_2d (0 0 */2 * *)
2016-12-31 00:00:00 +0100
2017-01-01 00:00:00 +0100
2017-01-03 00:00:00 +0100
2017-01-05 00:00:00 +0100
2017-01-07 00:00:00 +0100
2017-01-09 00:00:00 +0100
2017-01-11 00:00:00 +0100
2017-01-13 00:00:00 +0100
2017-01-15 00:00:00 +0100
2017-01-17 00:00:00 +0100

every_7d (0 0 * * 1)
2017-01-02 00:00:00 +0100
2017-01-09 00:00:00 +0100
2017-01-16 00:00:00 +0100
2017-01-23 00:00:00 +0100
2017-01-30 00:00:00 +0100
2017-02-06 00:00:00 +0100
2017-02-13 00:00:00 +0100
2017-02-20 00:00:00 +0100
2017-02-27 00:00:00 +0100
2017-03-06 00:00:00 +0100
```

### CODE REVIEW

File: lib/huginn_scheduler.rb [hunk 1]
```diff
@@ -96,6 +96,20 @@ class HuginnScheduler < LongRunnable::Worker
   include LongRunnable
 
   FAILED_JOBS_TO_KEEP = 100
+  SCHEDULE_TO_CRON = {
+    '1m'  => '*/1 * * * *',
+    '2m'  => '*/2 * * * *',
+    '5m'  => '*/5 * * * *',
+    '10m' => '*/10 * * * *',
+    '30m' => '*/30 * * * *',
+    '1h'  => '0 */1 * * *',
```
Comment (cantino) [inline lib/huginn_scheduler.rb]: Is this the same as `'0 * * * *'`?

File: app/models/agent.rb [hunk 2]
```diff
@@ -19,8 +19,8 @@ class Agent < ActiveRecord::Base
 
   load_types_in "Agents"
 
-  SCHEDULES = %w[every_1m every_2m every_5m every_10m every_30m every_1h every_2h every_5h every_12h every_1d every_2d every_7d
-                 midnight 1am 2am 3am 4am 5am 6am 7am 8am 9am 10am 11am noon 1pm 2pm 3pm 4pm 5pm 6pm 7pm 8pm 9pm 10pm 11pm never]
+  SCHEDULES = %w[every_1m every_2m every_5m every_10m every_30m every_1h every_2h every_5h every_12h every_1d every_2d] + [OpenStruct.new(to_s: 'every_7d', humanize: 'Every Monday')] +
```
Comment (cantino) [inline app/models/agent.rb]: Where does `humanize` get called? I guess this won't require a migration for Agents using every_7d because the db string won't change?

File: lib/huginn_scheduler.rb (hunk 1 above)
Comment (dsander) [inline lib/huginn_scheduler.rb]: I believe it is :)

File: app/models/agent.rb (hunk 2 above)
Comment (dsander) [inline app/models/agent.rb]: It's used in [scenario_import.rb](https://github.com/cantino/huginn/blob/master/app/importers/scenario_import.rb#L273) and the [agent form](https://github.com/cantino/huginn/blob/master/app/views/agents/_form.html.erb#L48), do you think it would be cleaner to convert the array to a hash with the humanized names set explicitly for all schedules?
Right, I wanted to avoid a migration since the "name" is only used internally.

**Comment by dsander** [comment]
I am waiting for a new `rufus-scheduler` version which should be released in the next days.

File: app/models/agent.rb (hunk 2 above)
Comment (cantino) [inline app/models/agent.rb]: That makes sense. Might be worth a comment, but I don't feel strongly.
