### PR TITLE
[fix #1512] add `not in` comparison into Trigger Agent

### LINKED ISSUE #1512: Incorrect (?) Trigger Agent behaviour for negative comparison
Maybe Travel Agent should parse rule `{"type": "field!=value", "value": [1,2], "path": "p"}` as `p != 1 and p != 2`, instead of `p != 1 or p != 2`? Same for `!regex`. Because in current behaviour value `1` will pass the rule. Yep, it's `by design` (and it's possible to make a workaround by creating one `!=` rule for each required value), but it's still quite strange behaviour, imho.

Or, at least, will be great if you just add an error (with an example of doing the thing in proper way) when adding `!` rule with array as value.

### PR DESCRIPTION
**Pull request by andrey-yantsen**
Add `not in` comparison for doing `!=` on arrays. Also warning about `!=` and arrays was added.
Fixes #1512.

### CODE REVIEW

File: app/models/agents/trigger_agent.rb [hunk 1]
```diff
@@ -11,7 +11,7 @@ class TriggerAgent < Agent
 
       The `type` can be one of #{VALID_COMPARISON_TYPES.map { |t| "`#{t}`" }.to_sentence} and compares with the `value`.  Note that regex patterns are matched case insensitively.  If you want case sensitive matching, prefix your pattern with `(?-i)`.
 
-      The `value` can be a single value or an array of values. In the case of an array, if one or more values match then the rule matches.
+      The `value` can be a single value or an array of values (all values must be stored as strings). In the case of an array, if one or more values match then the rule matches. *Warning*: avoid using `field!=value` with arrays, you should use `not in` instead.
```
Comment (cantino) [inline app/models/agents/trigger_agent.rb]: maybe "(in which case, all items in the array must be strings)"?

Comment (cantino) [inline app/models/agents/trigger_agent.rb]: More complete re-write:

The `value` can be a single value or an array of values. In the case of an array, all items must be strings, and if one or more values match, then the rule matches. Note: avoid using `field!=value` with arrays, you should use `not in` instead.

File: app/models/agents/trigger_agent.rb [hunk 2]
```diff
@@ -75,26 +75,30 @@ def receive(incoming_events)
...
-            when "field==value"
-              value_at_path.to_s == rule_value.to_s
-            when "field!=value"
-              value_at_path.to_s != rule_value.to_s
-            else
-              raise "Invalid type of #{rule['type']} in TriggerAgent##{id}"
+          if rule['type'] == 'not in'
+            rule_values.include?(value_at_path.to_s)
+          else
+            rule_values.any? do |rule_value|
```
Comment (cantino) [inline app/models/agents/trigger_agent.rb]: Could you convert this to an `if`...`elsif`` block instead of wrapping it in a new `if`?

**Comment by cantino** [comment]
Thanks @andrey-yantsen, would you mind updating the spec too?

File: app/models/agents/trigger_agent.rb (hunk 2 above)
Comment (andrey-yantsen) [inline app/models/agents/trigger_agent.rb]: Can you show me an example? I'm not very good with Ruby.

**Comment by andrey-yantsen** [comment]
Updating spec was a great idea :)
Give me an example for proper rewriting of `rule_values.any?` and I'll squash commits into one.

**Comment by cantino** [comment]
Maybe just this?

```ruby
rule_values.any? do |rule_value|
  if rule['type'] == "regex"
    value_at_path.to_s =~ Regexp.new(rule_value, Regexp::IGNORECASE)
  elsif rule['type'] == "!regex"
    value_at_path.to_s !~ Regexp.new(rule_value, Regexp::IGNORECASE)
  elsif rule['type'] == "field>value"
    value_at_path.to_f > rule_value.to_f
  elsif rule['type'] == "field>=value"
    value_at_path.to_f >= rule_value.to_f
  elsif rule['type'] == "field<value"
    value_at_path.to_f < rule_value.to_f
  elsif rule['type'] == "field<=value"
    value_at_path.to_f <= rule_value.to_f
  elsif rule['type'] == "field==value"
    value_at_path.to_s == rule_value.to_s
  elsif rule['type'] == "field!=value"
    value_at_path.to_s != rule_value.to_s
  elsif rule['type'] == 'in'
    rule_values.include?(value_at_path.to_s)
  elsif rule['type'] == 'not in'
    !rule_values.include?(value_at_path.to_s)
  else
    raise "Invalid type of #{rule['type']} in TriggerAgent##{id}"
  end
end
```

I added `in` there too.

**Comment by andrey-yantsen** [comment]
I can not agree with it :) It's quite strange to compare entire list inside `rule_values.any?` — according to your suggestion exactly same operation will be performed for each element of the list. Also — `.include?` operation should actually be performed for any `==`.

**Comment by cantino** [comment]
You're right, I misunderstood.

Want to add `in` next to your `not in` option at the top of the `if`?

**Comment by andrey-yantsen** [comment]
Actually `in` is quite strange operation because it is exactly the same thing as `field==value`. I've added it, but I'm confused a little by this decision :)

**Comment by cantino** [comment]
Yea, that's a good point.  I'm tired this evening.  We don't need it :)

**Comment by andrey-yantsen** [comment]
Ok :)
I've squashed the commits into one, check it once again please.

**Comment by cantino** [comment]
Thanks @andrey-yantsen, works great!
